################ USUARIOS

### BUSCAR TODOS OS USUARIOS

GET http://localhost:3048/api/user/all

### CADASTRAR NOVO USUARIO

POST http://localhost:3048/api/user/create
Content-Type: application/json

{
  "tipo": "fornecedor",
  "cpfcnpj": "12345678900",
  "nome": "Doria",
  "telefone": "(99) 991745323",
  "endereco": "Rua dr jose maria whitaker",
  "email": "fornecedor@gmail.com",
  "senha": "giovana0407",
  "status":"Ativo"
}

### BUSCAR UM USUARIO POR ID

POST http://localhost:3048/api/user/get
Content-Type: application/json

{
  "id": 3
}

### BUSCAR UM USUARIO POR TIPO

POST http://localhost:3048/api/user/getAlltipo
Content-Type: application/json

{
  "tipo": "fornecedor"
}

### DELETAR UM USUARIO POR ID

DELETE http://localhost:3048/api/user/delete
Content-Type: application/json

{
  "id": 1
}


################ SERVICOS

### BUSCAR TODOS OS SERVICOS

GET http://localhost:3048/api/servicos/all

### CADASTRAR NOVO SERVICO

POST http://localhost:3048/api/servicos/create
Content-Type: application/json

{
  "nome": "Extração de dente",
  "descricao": "Extração de dente",
  "preco_avulso": 50,
  "preco_convenio": 50,
  "status": "ativo"
}

### BUSCAR UM SERVIÇO POR ID

POST http://localhost:3048/api/servicos/get
Content-Type: application/json

{
  "id": 2
}

### DELETAR UM SERVIÇO POR ID

DELETE http://localhost:3048/api/servicos/delete
Content-Type: application/json

{
  "id": 5
}


################ OS

### BUSCAR TODOS AS OS

GET http://localhost:3048/api/os/all

### CADASTRAR NOVO OS

POST http://localhost:3048/api/os/create
Content-Type: application/json

{
  "servico_id": 1,
  "cliente_id": 2,
  "funcionario_id": 2,
  "convenio_id": 2,
  "QTparcelas": 4,
  "valorServico": 48,
  "valorDesconto": 48,
  "dataServico": "24/08/2024",
  "horaServico": "08:00",
  "salaServico": "7",
  "status":"Aguardando",
  "parcelas": [
    {
      "parcela": 1,
      "valorParcela": 48,
      "dataPagamento": "24/09/2024",
      "status": "Pendente"
    },
        {
      "parcela": 2,
      "valorParcela": 48,
      "dataPagamento": "24/10/2024",
      "status": "Pendente"
    },
        {
      "parcela": 3,
      "valorParcela": 48,
      "dataPagamento": "24/11/2024",
      "status": "Pendente"
    }
  ]
}


### BUSCAR UMA OS POR ID

POST http://localhost:3048/api/os/get
Content-Type: application/json

{
  "id": 7
}

### DELETAR UMA OS POR ID

DELETE http://localhost:3048/api/os/delete
Content-Type: application/json

{
  "id": 4
}

### PARCELAS

### BUSCAR TODAS AS PARCELAS
GET http://localhost:3048/api/parcelas/all

### BUSCAR PARCELA POR ID

POST http://localhost:3048/api/parcelas/id
Content-Type: application/json

{
  "id": 4
}

### BUSCAR PARCELA POR ID DA OS

POST http://localhost:3048/api/parcelas/idOs
Content-Type: application/json

{
  "os_id": 9
}

### DELETAR PARCELA POR ID

DELETE http://localhost:3048/api/parcelas/delete
Content-Type: application/json

{
  "id": 1
}

### ESTOQUE

### BUSCAR TODOS AS ESTOQUE
GET http://localhost:3048/api/estoque/all

### CADASTRAR NOVO ESTOQUE

POST http://localhost:3048/api/estoque/create
Content-Type: application/json

{
  "nome": "Espátula",
  "quantidade": 2,
  "fornecedor_id": 9,
  "categoria_id": 2
}

### BUSCAR ESTOQUE POR ID

POST http://localhost:3048/api/estoque/get
Content-Type: application/json

{
  "id": 1
}

### BUSCAR ESTOQUE POR ID DA CATEGORIA

POST http://localhost:3048/api/estoque/AllCategoria
Content-Type: application/json

{
  "categoria_id": 2
}

### BUSCAR ESTOQUE POR ID DO FORNECEDOR

POST http://localhost:3048/api/estoque/AllFornecedor
Content-Type: application/json

{
  "fornecedor_id": 9
}

### DELETAR ESTOQUE POR ID

DELETE http://localhost:3048/api/estoque/delete
Content-Type: application/json

{
  "id": 1
}

### CATEGORIA

### BUSCAR TODOS AS CATEGORIA
GET http://localhost:3048/api/categoria/all

### CADASTRAR NOVO OS

POST http://localhost:3048/api/categoria/create
Content-Type: application/json

{
  "nome": "Materias"
}

### BUSCAR CATEGORIA POR ID

POST http://localhost:3048/api/categoria/get
Content-Type: application/json

{
  "id": 1
}


### DELETAR CATEGORIA POR ID

DELETE http://localhost:3048/api/categoria/delete
Content-Type: application/json

{
  "id": 1
}


### HISTORICO DE ESTOQUE

### BUSCAR TODOS OS HISTORICOS DE ESTOQUE
GET http://localhost:3048/api/historic/all

### CADASTRAR NOVO HISTORICO DE ESTOQUE

POST http://localhost:3048/api/historic/create
Content-Type: application/json

{
  "tipo": "Saída",
  "quantidade": 2,
  "estoque_id": 1
}

### BUSCAR HISTORICO DE ESTOQUE POR ID

POST http://localhost:3048/api/historic/get
Content-Type: application/json

{
  "id": 1
}

### BUSCAR HISTORICO DE ESTOQUE POR ID DE UM ESTOQUE

POST http://localhost:3048/api/historic/AllEstoque
Content-Type: application/json

{
  "estoque_id": 1
}



### DELETAR HISTORICO DE ESTOQUE POR ID

DELETE http://localhost:3048/api/historic/delete
Content-Type: application/json

{
  "id": 4
}